package dev.avelissesolutions.avelisse.ime.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import dev.avelissesolutions.avelisse.core.theme.AvelisseColors
import dev.avelissesolutions.avelisse.core.theme.LocalAvelisseColors
import androidx.compose.material3.MaterialTheme
import dev.avelissesolutions.avelisse.core.ui.WaveformBars
import dev.avelissesolutions.avelisse.core.ui.WaveformDriver

/**
 * Transcribing overlay shown while whisper.cpp processes audio.
 *
 * Reuses the same 30-bar WaveformBars as RecordingScreen, but in processing
 * mode: a traveling sine wave generated by WaveformDriver.processingEnergy().
 * This matches the iOS BrandWaveform's isProcessing mode exactly.
 *
 * The WaveformDriver advances processingPhase each frame using the same
 * formula as iOS (link.duration / 2.0), producing smooth lateral wave motion.
 *
 * Total height: 310.dp (matching RecordingScreen and KeyboardScreen)
 * Layout: empty top row (46.dp) + center with waveform + label (218.dp) + empty bottom row (46.dp)
 */
@Composable
fun TranscribingScreen(
    modifier: Modifier = Modifier,
) {
    // Dedicated driver for processing animation.
    // The driver advances processingPhase per-frame via runLoop().
    val driver = remember {
        WaveformDriver().apply { isProcessing = true }
    }

    val phase by driver.processingPhase.collectAsState()

    // Run the driver's animation loop. Cancels automatically when this
    // composable leaves composition (i.e. when state changes from Transcribing).
    LaunchedEffect(Unit) {
        driver.runLoop()
    }

    Column(
        modifier = modifier.fillMaxWidth(),
    ) {
        // Top spacer (46.dp) — no buttons during transcription
        Spacer(
            modifier = Modifier
                .fillMaxWidth()
                .height(46.dp)
                .background(MaterialTheme.colorScheme.background),
        )

        // Center (218.dp) — animated waveform bars + label
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .height(218.dp)
                .background(MaterialTheme.colorScheme.background),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
        ) {
            // Animated waveform bars in processing mode.
            // WaveformBars reads processingPhase and computes the sine
            // wave per-bar via WaveformDriver.processingEnergy().
            WaveformBars(
                energyLevels = emptyList(),
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp)
                    .height(100.dp),
                isProcessing = true,
                processingPhase = phase,
            )

            // "Transcription..." label
            Text(
                text = stringResource(dev.avelissesolutions.avelisse.ime.R.string.ime_transcribing),
                color = LocalAvelisseColors.current.keyText.copy(alpha = 0.6f),
                fontSize = 13.sp,
                modifier = Modifier.padding(top = 16.dp),
            )
        }

        // Bottom spacer (46.dp)
        Spacer(
            modifier = Modifier
                .fillMaxWidth()
                .height(46.dp)
                .background(MaterialTheme.colorScheme.background),
        )
    }
}
